FROM docker.io/nvidia/cuda:12.2.2-devel-ubi9

ENV CUDA_HOME=/usr/local/cuda

RUN export ARCH="$(uname -m)" && \
    yum install -y git make gcc-toolset-12 python3.12-pip python3.12 python3.12-devel unzip java-11-openjdk java-11-openjdk-devel zip cmake wget && \
    export PATH="/opt/rh/gcc-toolset-12/root/usr/bin:${PATH}" && \
    export GCC_HOME="/opt/rh/gcc-toolset-12/root/usr" && \
    echo "PATH="${PATH}"" >> ${HOME}/.profile && \
    echo "PATH="${PATH}"" >> ${HOME}/.bashrc && \
    echo "GCC_HOME="${GCC_HOME}"" >> ${HOME}/.bashrc
